name: 🚥 iOS Build
on: push

jobs:
  tests:
    name: 🔨 Building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      # Smaller cache size
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        name: 🧾 Checkout

      - uses: actions/setup-dotnet@v4
        name: 💽 Setup .NET SDK
        with:
          dotnet-version: '8.0.107'

      - name: 📦 Restore Dependencies
        run: dotnet restore

      - uses: chickensoft-games/setup-godot@v2
        name: 🤖 Setup Godot
        with:
          version: 4.5.0-beta.1 # beta.4 for some reason has issues
          use-dotnet: true
          include-templates: true

      - name: 🧑‍🔬 Generate .NET Bindings
        run: godot --headless --build-solutions --quit || exit 0

      - name: 🦺 Build Projects
        run: dotnet build --configuration Debug

      - name: 📦 Export Game (MacOS Headless)
        run: |
            mkdir -p ios_export
            godot --headless --export-debug "iOS" ios_export/iode.zip
      
      - name: 📦 Compiling ipa
        run: | 
            cd ios_export
            xcodebuild archive -project iode.xcodeproj -scheme 'iode' -archivePath Iode-Project.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

            mkdir Payload
            mv Iode-Project.xcarchive/Products/Applications/iode.app Payload/iode.app

            zip -r "Iode.ipa" "Payload"

            mv Iode.ipa ${{ runner.temp }}/Iode.ipa
        
      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: Iode-Project
          path: ${{ runner.temp }}/Iode-Project.xcarchive
          retention-days: 3